url: "https://gauravmm.github.io/"
baseurl: "/AI6Lagos/"
title: Practical Data Science
description: CMU 15-388/688 Spring 2019

theme: jekyll-theme-cayman

# --- Navigation bar options --- #
navbar:
  - text: "Information"
    url: "/information"
  - text: "Lectures"
    url: "/lectures"
  - text: "Assignments"
    url: "/assignments"
  - text: "Calendar"
    url: "/calendar"
  - text: "Staff"
    url: "/staff"
  - text: "Policies"
    url: "/policies"
  - text: "FAQ"
    url: "/faq"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
# avatar: "/img/avatar-icon.png"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
# title-img: /path/to/image

# --- Footer options --- #
author:
  name: Practical Data Science
  email: "gmanek@cs.cmu.edu"

show_downloads: false
#google_analytics: ""

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/NewYork"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/

kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: "notes"
    values:
      layout: "notes"
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true
      bigimg: 
        - /img/datascience-bg.jpg

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Vagrantfile
